apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-crd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.global.spec.destination.server | default "https://kubernetes.default.svc" }}
  project: {{ .Values.gatewayCRD.spec.project | default "default" }}
  source:
    path: config/crd/standard/
    repoURL: https://github.com/kubernetes-sigs/gateway-api/
    targetRevision: {{ .Values.gatewayCRD.spec.source.targetRevision | default "v1.3.0" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true