apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sealedSecrets.spec.destination.namespace | default "sealed-secrets" }}
  labels:
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.sealedSecrets.spec.destination.namespace | default "sealed-secrets" }}
    server: {{ .Values.global.spec.destination.server | default "https://kubernetes.default.svc" }}
  project: {{ .Values.sealedSecrets.spec.destination.project | default "default" }}
  source:
    path: k8s/apps/sealed-secrets
    repoURL: https://github.com/RangersMS/homelab
    targetRevision: {{ .Values.global.spec.source.targetRevision | default "main" }}
    helm:
      valueFiles:
      - values.yaml
      ignoreMissingValueFiles: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true