global:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      targetRevision: main

sealedSecrets:
  spec:
    destination:
      namespace: sealed-secrets
    project: default

istio:
  spec:
    destination:
      namespace: istio-system
    project: default

certManager:
  spec:
    destination:
      namespace: cert-manager
    project: default

gatewayCRD:
  spec:
    project: default
    source:
      targetRevision: v1.3.0