apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgB5sd6AC2oEvsWZYLkflFXTrZl1gSKD75/87VarapZd3lJP1bo8wqfpEq0nznXyPBwxlAcU/K5L7l8nCIt9iHoEsls/e4ya9sjJZmVZu25cqQizLTLlnDqr50zUfUL21vmPAsUzn0tf1MMyyf4Z5+Q5HDf1IZQwOB99gy2175ubXID/6bbjryIHEzFVm4ZZt82WKZSwBTi5IunJTjbPnJIuqPAGEgq3Z9xcCzVfiul78ZytSrAPukKRGavizVfNr8x6rps4pBGPprr12D+uaKpUGEMM5dDnt+vpRqAaYlCPe+a6BDtpYgfpqZ/cGQj6v5woP6qsIU/xxKJosDe1vKI3xQuqx42EWv/YUUqq4ANVefrDcSRwgKFVRWaI4DBUfzWiQl0JShaJEoMhuFl7uZiHhWN0FETxRFRwNOsJ7Yr51h/pSRUx78kpK8MhJOLQr3JrxEzPmeOQ5NM81OvsWY1ZytoOsdi0egdncaRdczmEP4nN57NBBZKmwI664xgJ5K84/f5hbpG+FBGFEB2RCU620NwBULzxy41y+lqd+VXLWiyNuMZixmR1izVP/Vx/s9J7AwgMcU52xvpyiN0BOly8pAh243qvtV2hsNY6B1LSSMib7oeLIiYdjYJPJ5yPXdylddO/b6eZQg64WKdf/F9Z4JdyWklGYS2AYftZrOZ0G8Y/kOdqUqboHbdAUbv/V5LV5ViLJHacJrEq2ksdyUL0Uno4NFIAD5fUjBsKNYHEC9pjUfxT39JA
  template:
    metadata:
      name: cloudflare-api-token-secret
    type: Opaque
